### ISSUE TITLE
typst doesnt process  correctly the content 

### ISSUE THREAD

**Issue by danieltomasz** [mintyfrankie/awesomeCV-Typst#6]
I download the repo and try to compile one of the document
```
cd modules_fr && quarto typst compile MyCV.typ
```
Ther result is below
![image](https://github.com/mintyfrankie/awesomeCV-Typst/assets/7980381/bd0969b1-75ca-4536-a619-c92303304258)

I am on MacOS 13.4.1, typst 0.6.0

**Comment by danieltomasz** [comment]
I tried to compile it in wrong directory, I am closing it 

Thanks for providing nice templates!

**Comment by danieltomasz** [comment]
It compiles correctly, but I am still wrapping my head how to compile the french one, or how to compile english one without comic sans/xkcd  style 

![image](https://github.com/mintyfrankie/awesomeCV-Typst/assets/7980381/dcfbd059-5b52-4640-b0bc-a7bff5e0e156)

**Comment by danieltomasz** [comment]
I was able to use Roboto in the the template, so I can play with other values as well, but how I can get other values for the french CV in README?

**Comment by mintyfrankie** [comment]
Hi @danieltomasz what exactly are your needs right now? What do you mean by getting other values in README?
