### ISSUE TITLE
Compile with a multilanguage module

### ISSUE THREAD

**Issue by barbem** [mintyfrankie/awesomeCV-Typst#7]
It is possible to create multiple modules directories for each language like modules_fr in this repo. When I compile the CV, the main modules directory is used to produce english document. How can I specify the language to compile my CV to another language?

**Comment by mintyfrankie** [comment]
Try modifying the `varLanguage` variable in `metadata.typ`.

**Comment by barbem** [comment]
Thank you. I edited this variable, but some files are missing in modules_fr folder. After copying certificats and publication missing files to modules_fr folder, the fr CV can be generated.
